<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Contact\Block\ContactForm $block */
?>
<form class="form contact"
      action="<?= $block->escapeUrl($block->getFormAction()) ?>"
      id="contact-form"
      method="post"
      data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset">
        <legend class="legend"><span><?= $block->escapeHtml(__('Write Us')) ?></span></legend><br />
        <div class="field note no-label"><?= $block->escapeHtml(__('Jot us a note and we’ll get back to you as quickly as possible.')) ?></div>
        <div class="field name required">
            <label class="label" for="name"><span><?= $block->escapeHtml(__('Name')) ?></span></label>
            <div class="control">
                <input name="name" id="name" title="<?= $block->escapeHtmlAttr(__('Name')) ?>" value="<?= $block->escapeHtmlAttr($this->helper(\Magento\Contact\Helper\Data::class)->getPostValue('name') ?: $this->helper(\Magento\Contact\Helper\Data::class)->getUserName()) ?>" class="input-text" type="text" data-validate="{required:true}"/>
            </div>
        </div>
        <div class="field email required">
            <label class="label" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
            <div class="control">
                <input name="email" id="email" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" value="<?= $block->escapeHtmlAttr($this->helper(\Magento\Contact\Helper\Data::class)->getPostValue('email') ?: $this->helper(\Magento\Contact\Helper\Data::class)->getUserEmail()) ?>" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/>
            </div>
        </div>
        <div class="field telephone">
            <label class="label" for="telephone"><span><?= $block->escapeHtml(__('Phone Number')) ?></span></label>
            <div class="control">
                <input name="telephone" id="telephone" title="<?= $block->escapeHtmlAttr(__('Phone Number')) ?>" value="<?= $block->escapeHtmlAttr($this->helper(\Magento\Contact\Helper\Data::class)->getPostValue('telephone')) ?>" class="input-text" type="text" />
            </div>
        </div>
		<!---custom fields--->
		<div class="field city">
   <label class="label" for="city"><span><?= $block->escapeHtml(__('City')) ?></span></label>
   <div class="control">
       <input name="city" id="city" title="<?= $block->escapeHtml(__('city')) ?>" class="input-text" type="text" />
   </div>
</div>
		
		
		<div class="field country ">
   <label class="label" for="country"><span><?= $block->escapeHtml(__('Country')) ?></span></label>
   <div class="control">
       <select name="country" >
           <option disabled selected hidden value=""><?= $block->escapeHtml(__('Choose a Country')) ?></option>

    <option value="Afghanistan"><?= $block->escapeHtml(__('Afghanistan')) ?></option>
    <option value="Albania"><?= $block->escapeHtml(__('Albania')) ?></option>
    <option value="Algeria"><?= $block->escapeHtml(__('Algeria')) ?></option>
    <option value="American Samoa"><?= $block->escapeHtml(__('American Samoa')) ?></option>
    <option value="Andorra"><?= $block->escapeHtml(__('Andorra')) ?></option>
    <option value="Angola"><?= $block->escapeHtml(__('Angola')) ?></option>
    <option value="Anguilla"><?= $block->escapeHtml(__('Anguilla')) ?></option>
    <option value="Antartica"><?= $block->escapeHtml(__('Antarctica')) ?></option>
    <option value="Antigua and Barbuda"><?= $block->escapeHtml(__('Antigua and Barbuda')) ?></option>
    <option value="Argentina"><?= $block->escapeHtml(__('Argentina')) ?></option>
    <option value="Armenia"><?= $block->escapeHtml(__('Armenia')) ?></option>
    <option value="Aruba"><?= $block->escapeHtml(__('Aruba')) ?></option>
    <option value="Australia"><?= $block->escapeHtml(__('Australia')) ?></option>
    <option value="Austria"><?= $block->escapeHtml(__('Austria')) ?></option>
    <option value="Azerbaijan"><?= $block->escapeHtml(__('Azerbaijan')) ?></option>
    <option value="Bahamas"><?= $block->escapeHtml(__('Bahamas')) ?></option>
    <option value="Bahrain"><?= $block->escapeHtml(__('Bahrain')) ?></option>
    <option value="Bangladesh"><?= $block->escapeHtml(__('Bangladesh')) ?></option>
    <option value="Barbados"><?= $block->escapeHtml(__('Barbados')) ?></option>
    <option value="Belarus"><?= $block->escapeHtml(__('Belarus')) ?></option>
    <option value="Belgium"><?= $block->escapeHtml(__('Belgium')) ?></option>
    <option value="Belize"><?= $block->escapeHtml(__('Belize')) ?></option>
    <option value="Benin"><?= $block->escapeHtml(__('Benin')) ?></option>
    <option value="Bermuda"><?= $block->escapeHtml(__('Bermuda')) ?></option>
    <option value="Bhutan"><?= $block->escapeHtml(__('Bhutan')) ?></option>
    <option value="Bolivia"><?= $block->escapeHtml(__('Bolivia')) ?></option>
    <option value="Bosnia and Herzegowina"><?= $block->escapeHtml(__('Bosnia and Herzegowina')) ?></option>
    <option value="Botswana"><?= $block->escapeHtml(__('Botswana')) ?></option>
    <option value="Bouvet Island"><?= $block->escapeHtml(__('Bouvet Island')) ?></option>
    <option value="Brazil"><?= $block->escapeHtml(__('Brazil')) ?></option>
    <option value="British Indian Ocean Territory"><?= $block->escapeHtml(__('British Indian Ocean Territory')) ?></option>
    <option value="Brunei Darussalam"><?= $block->escapeHtml(__('Brunei Darussalam')) ?></option>
    <option value="Bulgaria"><?= $block->escapeHtml(__('Bulgaria')) ?></option>
    <option value="Burkina Faso"><?= $block->escapeHtml(__('Burkina Faso')) ?></option>
    <option value="Burundi"><?= $block->escapeHtml(__('Burundi')) ?></option>
    <option value="Cambodia"><?= $block->escapeHtml(__('Cambodia')) ?></option>
    <option value="Cameroon"><?= $block->escapeHtml(__('Cameroon')) ?></option>
    <option value="Canada"><?= $block->escapeHtml(__('Canada')) ?></option>
    <option value="Cape Verde"><?= $block->escapeHtml(__('Cape Verde')) ?></option>
    <option value="Cayman Islands"><?= $block->escapeHtml(__('Cayman Islands')) ?></option>
    <option value="Central African Republic"><?= $block->escapeHtml(__('Central African Republic')) ?></option>
    <option value="Chad"><?= $block->escapeHtml(__('Chad')) ?></option>
    <option value="Chile"><?= $block->escapeHtml(__('Chile')) ?></option>
    <option value="China"><?= $block->escapeHtml(__('China')) ?></option>
    <option value="Christmas Island"><?= $block->escapeHtml(__('Christmas Island')) ?></option>
    <option value="Cocos Islands"><?= $block->escapeHtml(__('Cocos (Keeling) Islands')) ?></option>
    <option value="Colombia"><?= $block->escapeHtml(__('Colombia')) ?></option>
    <option value="Comoros"><?= $block->escapeHtml(__('Comoros')) ?></option>
    <option value="Congo"><?= $block->escapeHtml(__('Congo')) ?></option>
    <option value="Congo"><?= $block->escapeHtml(__('Congo, the Democratic Republic of the')) ?></option>
    <option value="Cook Islands"><?= $block->escapeHtml(__('Cook Islands')) ?></option>
    <option value="Costa Rica"><?= $block->escapeHtml(__('Costa Rica')) ?></option>
    <option value="Cota D'Ivoire"><?= $block->escapeHtml(__('Cote d Ivoire')) ?></option>
    <option value="Croatia"><?= $block->escapeHtml(__('Croatia (Hrvatska)')) ?></option>
    <option value="Cuba"><?= $block->escapeHtml(__('Cuba')) ?></option>
    <option value="Cyprus"><?= $block->escapeHtml(__('Cyprus')) ?></option>
    <option value="Czech Republic"><?= $block->escapeHtml(__('Czech Republic')) ?></option>
    <option value="Denmark"><?= $block->escapeHtml(__('Denmark')) ?></option>
    <option value="Djibouti"><?= $block->escapeHtml(__('Djibouti')) ?></option>
    <option value="Dominica"><?= $block->escapeHtml(__('Dominica')) ?></option>
    <option value="Dominican Republic"><?= $block->escapeHtml(__('Dominican Republic')) ?></option>
    <option value="East Timor"><?= $block->escapeHtml(__('East Timor')) ?></option>
    <option value="Ecuador"><?= $block->escapeHtml(__('Ecuador')) ?></option>
    <option value="Egypt"><?= $block->escapeHtml(__('Egypt')) ?></option>
    <option value="El Salvador"><?= $block->escapeHtml(__('El Salvador')) ?></option>
    <option value="Equatorial Guinea"><?= $block->escapeHtml(__('Equatorial Guinea')) ?></option>
    <option value="Eritrea"><?= $block->escapeHtml(__('Eritrea')) ?></option>
    <option value="Estonia"><?= $block->escapeHtml(__('Estonia')) ?></option>
    <option value="Ethiopia"><?= $block->escapeHtml(__('Ethiopia')) ?></option>
    <option value="Falkland Islands"><?= $block->escapeHtml(__('Falkland Islands (Malvinas)')) ?></option>
    <option value="Faroe Islands"><?= $block->escapeHtml(__('Faroe Islands')) ?></option>
    <option value="Fiji"><?= $block->escapeHtml(__('Fiji')) ?></option>
    <option value="Finland"><?= $block->escapeHtml(__('Finland')) ?></option>
    <option value="France"><?= $block->escapeHtml(__('France')) ?></option>
    <option value="France Metropolitan"><?= $block->escapeHtml(__('France, Metropolitan')) ?></option>
    <option value="French Guiana"><?= $block->escapeHtml(__('French Guiana')) ?></option>
    <option value="French Polynesia"><?= $block->escapeHtml(__('French Polynesia')) ?></option>
    <option value="French Southern Territories"><?= $block->escapeHtml(__('French Southern Territories')) ?></option>
    <option value="Gabon"><?= $block->escapeHtml(__('Gabon')) ?></option>
    <option value="Gambia"><?= $block->escapeHtml(__('Gambia')) ?></option>
    <option value="Georgia"><?= $block->escapeHtml(__('Georgia')) ?></option>
    <option value="Germany">Germany</option>
    <option value="Ghana">Ghana</option>
    <option value="Gibraltar">Gibraltar</option>
    <option value="Greece">Greece</option>
    <option value="Greenland">Greenland</option>
    <option value="Grenada">Grenada</option>
    <option value="Guadeloupe">Guadeloupe</option>
    <option value="Guam">Guam</option>
    <option value="Guatemala">Guatemala</option>
    <option value="Guinea">Guinea</option>
    <option value="Guinea-Bissau">Guinea-Bissau</option>
    <option value="Guyana">Guyana</option>
    <option value="Haiti">Haiti</option>
    <option value="Heard and McDonald Islands">Heard and Mc Donald Islands</option>
    <option value="Holy See">Holy See (Vatican City State)</option>
    <option value="Honduras">Honduras</option>
    <option value="Hong Kong">Hong Kong</option>
    <option value="Hungary">Hungary</option>
    <option value="Iceland">Iceland</option>
    <option value="India">India</option>
    <option value="Indonesia">Indonesia</option>
    <option value="Iran">Iran (Islamic Republic of)</option>
    <option value="Iraq">Iraq</option>
    <option value="Ireland">Ireland</option>
    <option value="Israel">Israel</option>
    <option value="Italy">Italy</option>
    <option value="Jamaica">Jamaica</option>
    <option value="Japan">Japan</option>
    <option value="Jordan">Jordan</option>
    <option value="Kazakhstan">Kazakhstan</option>
    <option value="Kenya">Kenya</option>
    <option value="Kiribati">Kiribati</option>
    <option value="Democratic People's Republic of Korea">Korea, Democratic People's Republic of</option>
    <option value="Korea">Korea, Republic of</option>
    <option value="Kuwait">Kuwait</option>
    <option value="Kyrgyzstan">Kyrgyzstan</option>
    <option value="Lao">Lao People's Democratic Republic</option>
    <option value="Latvia">Latvia</option>
    <option value="Lebanon">Lebanon</option>
    <option value="Lesotho">Lesotho</option>
    <option value="Liberia">Liberia</option>
    <option value="Libyan Arab Jamahiriya">Libyan Arab Jamahiriya</option>
    <option value="Liechtenstein">Liechtenstein</option>
    <option value="Lithuania">Lithuania</option>
    <option value="Luxembourg">Luxembourg</option>
    <option value="Macau">Macau</option>
    <option value="Macedonia">Macedonia, The Former Yugoslav Republic of</option>
    <option value="Madagascar">Madagascar</option>
    <option value="Malawi">Malawi</option>
    <option value="Malaysia">Malaysia</option>
    <option value="Maldives">Maldives</option>
    <option value="Mali">Mali</option>
    <option value="Malta">Malta</option>
    <option value="Marshall Islands">Marshall Islands</option>
    <option value="Martinique">Martinique</option>
    <option value="Mauritania">Mauritania</option>
    <option value="Mauritius">Mauritius</option>
    <option value="Mayotte">Mayotte</option>
    <option value="Mexico">Mexico</option>
    <option value="Micronesia">Micronesia, Federated States of</option>
    <option value="Moldova">Moldova, Republic of</option>
    <option value="Monaco">Monaco</option>
    <option value="Mongolia">Mongolia</option>
    <option value="Montserrat">Montserrat</option>
    <option value="Morocco">Morocco</option>
    <option value="Mozambique">Mozambique</option>
    <option value="Myanmar">Myanmar</option>
    <option value="Namibia">Namibia</option>
    <option value="Nauru">Nauru</option>
    <option value="Nepal">Nepal</option>
    <option value="Netherlands">Netherlands</option>
    <option value="Netherlands Antilles">Netherlands Antilles</option>
    <option value="New Caledonia">New Caledonia</option>
    <option value="New Zealand">New Zealand</option>
    <option value="Nicaragua">Nicaragua</option>
    <option value="Niger">Niger</option>
    <option value="Nigeria">Nigeria</option>
    <option value="Niue">Niue</option>
    <option value="Norfolk Island">Norfolk Island</option>
    <option value="Northern Mariana Islands">Northern Mariana Islands</option>
    <option value="Norway">Norway</option>
    <option value="Oman">Oman</option>
    <option value="Pakistan">Pakistan</option>
    <option value="Palau">Palau</option>
    <option value="Panama">Panama</option>
    <option value="Papua New Guinea">Papua New Guinea</option>
    <option value="Paraguay">Paraguay</option>
    <option value="Peru">Peru</option>
    <option value="Philippines">Philippines</option>
    <option value="Pitcairn">Pitcairn</option>
    <option value="Poland">Poland</option>
    <option value="Portugal">Portugal</option>
    <option value="Puerto Rico">Puerto Rico</option>
    <option value="Qatar">Qatar</option>
    <option value="Reunion">Reunion</option>
    <option value="Romania">Romania</option>
    <option value="Russia">Russian Federation</option>
    <option value="Rwanda">Rwanda</option>
    <option value="Saint Kitts and Nevis">Saint Kitts and Nevis</option> 
    <option value="Saint LUCIA">Saint LUCIA</option>
    <option value="Saint Vincent">Saint Vincent and the Grenadines</option>
    <option value="Samoa">Samoa</option>
    <option value="San Marino">San Marino</option>
    <option value="Sao Tome and Principe">Sao Tome and Principe</option> 
    <option value="Saudi Arabia">Saudi Arabia</option>
    <option value="Senegal">Senegal</option>
    <option value="Seychelles">Seychelles</option>
    <option value="Sierra">Sierra Leone</option>
    <option value="Singapore">Singapore</option>
    <option value="Slovakia">Slovakia (Slovak Republic)</option>
    <option value="Slovenia">Slovenia</option>
    <option value="Solomon Islands">Solomon Islands</option>
    <option value="Somalia">Somalia</option>
    <option value="South Africa">South Africa</option>
    <option value="South Georgia">South Georgia and the South Sandwich Islands</option>
    <option value="Span">Spain</option>
    <option value="SriLanka">Sri Lanka</option>
    <option value="St. Helena">St. Helena</option>
    <option value="St. Pierre and Miguelon">St. Pierre and Miquelon</option>
    <option value="Sudan">Sudan</option>
    <option value="Suriname">Suriname</option>
    <option value="Svalbard">Svalbard and Jan Mayen Islands</option>
    <option value="Swaziland">Swaziland</option>
    <option value="Sweden">Sweden</option>
    <option value="Switzerland">Switzerland</option>
    <option value="Syria">Syrian Arab Republic</option>
    <option value="Taiwan">Taiwan, Province of China</option>
    <option value="Tajikistan">Tajikistan</option>
    <option value="Tanzania">Tanzania, United Republic of</option>
    <option value="Thailand">Thailand</option>
    <option value="Togo">Togo</option>
    <option value="Tokelau">Tokelau</option>
    <option value="Tonga">Tonga</option>
    <option value="Trinidad and Tobago">Trinidad and Tobago</option>
    <option value="Tunisia">Tunisia</option>
    <option value="Turkey">Turkey</option>
    <option value="Turkmenistan">Turkmenistan</option>
    <option value="Turks and Caicos">Turks and Caicos Islands</option>
    <option value="Tuvalu">Tuvalu</option>
    <option value="Uganda">Uganda</option>
    <option value="Ukraine">Ukraine</option>
    <option value="United Arab Emirates">United Arab Emirates</option>
    <option value="United Kingdom">United Kingdom</option>
    <option value="United States">United States</option>
    <option value="United States Minor Outlying Islands">United States Minor Outlying Islands</option>
    <option value="Uruguay">Uruguay</option>
    <option value="Uzbekistan">Uzbekistan</option>
    <option value="Vanuatu">Vanuatu</option>
    <option value="Venezuela">Venezuela</option>
    <option value="Vietnam">Viet Nam</option>
    <option value="Virgin Islands (British)">Virgin Islands (British)</option>
    <option value="Virgin Islands (U.S)">Virgin Islands (U.S.)</option>
    <option value="Wallis and Futana Islands">Wallis and Futuna Islands</option>
    <option value="Western Sahara">Western Sahara</option>
    <option value="Yemen">Yemen</option>
    <option value="Yugoslavia">Yugoslavia</option>
    <option value="Zambia">Zambia</option>
    <option value="Zimbabwe">Zimbabwe</option>
       </select>
	   
	
	   
	   
   </div>
</div>
		
		<!---//custom fields--->
		
		
        <div class="field comment required">
            <label class="label" for="comment"><span><?= $block->escapeHtml(__('What’s on your mind?')) ?></span></label>
            <div class="control">
                <textarea name="comment" id="comment" title="<?= $block->escapeHtmlAttr(__('What’s on your mind?')) ?>" class="input-text" cols="5" rows="3" data-validate="{required:true}"><?= $block->escapeHtml($this->helper(\Magento\Contact\Helper\Data::class)->getPostValue('comment')) ?></textarea>
            </div>
        </div>
        <?= $block->getChildHtml('form.additional.info') ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <input type="hidden" name="hideit" id="hideit" value="" />
            <button type="submit" title="<?= $block->escapeHtmlAttr(__('Submit')) ?>" class="action submit primary">
                <span><?= $block->escapeHtml(__('Submit')) ?></span>
            </button>
        </div>
    </div>
</form>
